import { useEffect, useMemo, useRef, useState } from 'react';
import type { Quest, QuestDataset, QuestTask, QuestBlock } from '../lib/quests';
import { capacityRods, fishMatch, rodMatch, fold, findQuests, questOptions, questTasks, questFilterDefaults, readQuestProgress, taskProgressKey } from '../lib/quest-search';
import type { QuestFilters } from '../lib/quest-search';
import '../styles/fish-database.css';
import '../styles/quest-helper.css';
const STORAGE='fisch-finder-quest-progress-v1';let visitProgress:Record<string,true>={};
const sourceUrl=(page:string)=>'https://fischipedia.org/wiki/'+encodeURIComponent(page.replace(/ /g,'_'));
const fishUrl=(page:string)=>`/?q=${encodeURIComponent(page)}&fish=${encodeURIComponent(page)}`;
const rodUrl=(page:string)=>`/rods?q=${encodeURIComponent(page)}&rod=${encodeURIComponent(page)}`;
const timestamp=(value:string)=>new Date(value).toISOString().replace('T',' ').replace(/\.\d{3}Z$/,' UTC');
const statusLabel=(status:string)=>status==='available'?'Available':status==='unavailable'?'Unavailable':'Check availability';
const pageSize=25;
function Blocks({blocks,data}:{blocks:QuestBlock[];data:QuestDataset}) {return <div className="quest-notes">{blocks.map((block,index)=><section key={index}><h3>{block.heading}</h3>{block.paragraphs.map((text,i)=><p key={i}>{text}</p>)}{block.tables.map((table,i)=><div className="quest-guide-table-wrap" key={i} tabIndex={0} role="region" aria-label={table.caption||block.heading}><table className="quest-guide-table"><caption>{table.caption||block.heading}</caption><thead><tr>{table.headers.map((label,j)=><th scope="col" key={j}>{label}</th>)}</tr></thead><tbody>{table.rows.map((row,j)=><tr key={j}>{row.map((text,k)=><td data-label={table.headers[k]} key={k}>{fishMatch(data,text)?<a href={fishUrl(fishMatch(data,text)!.page)}>{text} ↗</a>:text||'—'}</td>)}</tr>)}</tbody></table></div>)}</section>)}</div>;}
function CatchHelp({task,data}:{task:QuestTask;data:QuestDataset}) {
 const mutationRods=task.mutations.flatMap(name=>data.mutations.filter(m=>fold(m.name)===fold(name)||fold(m.page)===fold(name)).flatMap(m=>m.rods.map(r=>({...r,mutation:m.name}))));
 return <div className="quest-catch-help">
  {task.solutions?.map(solution=><p className="quest-info" key={solution}><strong>Wiki solution: </strong>{solution}</p>)}
  {mutationRods.length>0&&<article className="quest-catch-card"><h4>Mutation rods for this objective</h4><ul>{mutationRods.map((ref,i)=>{const rod=rodMatch(data,ref.page);return <li key={ref.mutation+ref.page+i}><a href={rodUrl(rod?.page??ref.page)}>{ref.name} ↗</a><span> · {ref.mutation}{rod?.level?` · level ${rod.level}`:''}</span>{rod?.unavailable&&<span className="quest-warning"> · marked unavailable</span>}</li>;})}</ul><p className="quest-hint">These rods provide mutation methods, not additional mandatory catches. Follow the objective’s combinations and alternatives; expand the mutation notes below for chances and conditions.</p></article>}
  {!task.fish.length&&!task.rods.length&&!task.mutations.length&&<p className="quest-hint">No specific fish or fishing rod is named for this objective. Follow its instructions and the guide notes; a dynamic target must be checked in your Quest Book.</p>}
  {task.fish.map(ref=>{const fish=fishMatch(data,ref.page);const rods=fish?capacityRods(data,fish):[];return <article className="quest-catch-card" key={ref.page+ref.attributes}><h4>{ref.quantity&&`${ref.quantity} × `}{ref.attributes&&`${ref.attributes.replace(/\s*,\s*/g,' + ')} `}{ref.name}</h4><p className="quest-hint">Follow the full objective above for quantities, alternatives, and mutation combinations.</p>{fish?<><dl className="quest-fish-facts"><div><dt>Where</dt><dd>{fish.location||'Not listed'}</dd></div><div><dt>Bait</dt><dd>{fish.bait.join(', ')||'No preference listed'}</dd></div><div><dt>Weather</dt><dd>{fish.weather.join(', ')||'No preference listed'}</dd></div><div><dt>Time / season</dt><dd>{[fish.time.join(', '),fish.season.join(', ')].filter(Boolean).join(' · ')||'No preference listed'}</dd></div>{fish.methods.length>0&&<div><dt>Method</dt><dd>{fish.methods.join(', ')}</dd></div>}</dl>{fish.unavailable&&<p className="quest-warning">This fish/item is marked unavailable in the wiki. Check the source before attempting this quest.</p>}{fish.maximumWeight!=null&&fish.maximumWeight>0&&<p className="quest-hint">Upper base weight: {fish.maximumWeight.toLocaleString('en-US')} kg. Mutations and weight bonuses can increase it.</p>}{rods.length>0&&!fish.methods.some(m=>/crab|mining|purchase/i.test(m))&&<div className="quest-rod-options"><strong>Capacity options</strong><ul>{rods.map(rod=><li key={rod.page}><a href={rodUrl(rod.page)}>{rod.name} ↗</a><span> {rod.weightLabel} kg{rod.level?` · level ${rod.level}`:''}</span></li>)}</ul><p className="quest-hint">Based on unmodified capacity only. Use the objective’s required rod and mutation method first; these options don’t guarantee a catch.</p></div>}</>:<p className="quest-hint">Catch preferences are not listed for this target. Check its wiki page and your Quest Book.</p>}<div className="quest-links"><a href={fishUrl(fish?.page??ref.page)}>Open Fish Finder ↗</a><a href={sourceUrl(ref.page)} target="_blank" rel="noopener noreferrer">Fish/item source ↗</a></div></article>;})}
  {task.rods.length>0&&<article className="quest-catch-card"><h4>Rods named in this objective</h4><ul>{task.rods.map(ref=>{const rod=rodMatch(data,ref.page);return <li key={ref.page}><a href={rodUrl(rod?.page??ref.page)}>{ref.name} ↗</a>{rod?.level&&<span> · level {rod.level}</span>}{rod?.unavailable&&<span className="quest-warning"> · marked unavailable</span>}</li>;})}</ul><p className="quest-hint">Keep the exact rod and any enchantment or mastery conditions in the objective above.</p></article>}
  {task.mutations.map(name=>{const mutation=data.mutations.find(m=>fold(m.name)===fold(name)||fold(m.page)===fold(name));return <details className="quest-mutation" key={name}><summary>{name}: mutation methods & rods</summary>{mutation?<><ul>{mutation.notes.map((text,i)=><li key={i}>{text}</li>)}</ul>{mutation.rods.length>0&&<div className="quest-links">{mutation.rods.map(r=><a key={r.page} href={rodUrl(rodMatch(data,r.page)?.page??r.page)}>{r.name} ↗</a>)}</div>}<a href={mutation.url} target="_blank" rel="noopener noreferrer">Full mutation source ↗</a></>:<p>Method not listed in this guide. <a href={sourceUrl(name)} target="_blank" rel="noopener noreferrer">Check the mutation source ↗</a></p>}<p className="quest-hint">A quest may require a fresh catch or forbid appraisal/trading. Its requirements take priority over these general mutation methods.</p></details>;})}
 </div>;
}
function Guide({quest,data,progress,toggle,storageAvailable,share,shareStatus}:{quest:Quest;data:QuestDataset;progress:Record<string,true>;toggle:(task:QuestTask)=>void;storageAvailable:boolean;share:()=>void;shareStatus:string}) {
 const [view,setView]=useState('guide');const tasks=questTasks(quest),done=tasks.filter(t=>progress[taskProgressKey(quest,t)]).length;
 const checklist=tasks,archived=quest.stages.filter(s=>s.archived);
 const stages=quest.stages.filter(s=>!s.archived);
 return <><div className="quest-guide-layout"><aside className="quest-guide-sidebar"><nav aria-label="Quest guide sections">{[['overview','Overview'],['guide','Step-by-step guide'],['checklist','Fish & rod checklist'],['rewards','Rewards']].map(([value,label])=><button key={value} aria-pressed={view===value} onClick={()=>setView(value)}>{label}</button>)}</nav><div className="quest-progress"><strong>Your progress</strong><p>{done} of {tasks.length} objectives complete</p><progress aria-label="Quest checklist progress" value={done} max={Math.max(1,tasks.length)}/><p className="quest-hint">{storageAvailable?'Saved on this device.':'Storage unavailable; kept for this visit.'} This checklist does not sync with Roblox.</p></div><button className="quest-share" onClick={share}>Copy guide link</button>{shareStatus&&<p className="quest-hint" role="status">{shareStatus}</p>}</aside>
 <div className="quest-guide-content" key={view}>
  {view==='overview'&&<><h2>Overview & prerequisites</h2><p>{quest.description||'See the quest giver and Quest Book for the current requirements.'}</p><dl className="quest-overview-facts"><div><dt>Quest giver</dt><dd>{quest.npc}</dd></div><div><dt>Location</dt><dd>{quest.locations.join(' · ')||'Not listed'}</dd></div><div><dt>GPS</dt><dd>{quest.gps||'Not listed'}</dd></div><div><dt>Event</dt><dd>{quest.events.join(' · ')||'No event listed'}</dd></div></dl><Blocks data={data} blocks={quest.notes.filter(b=>b.heading==='Requirements & guide notes')}/><p className="quest-info">Accept the quest before starting. Check level gates, prerequisite quests, and whether fish must be freshly caught. A quest collection can include separate or conditional quests; follow the source’s unlock order.</p></>}
  {view==='guide'&&<><h2>Step-by-step guide</h2><p className="quest-info">Quest giver: {quest.npc} · {quest.locations.join(' · ')||'Location not listed'}{quest.gps?` · GPS ${quest.gps}`:''}. Check Overview for prerequisites and the guide notes below for solutions.</p>{quest.incomplete&&<p className="quest-warning">The source has missing details or variable objectives. Confirm the current target, mutations, and timer in your in-game Quest Book.</p>}{stages.length?stages.map((stage,index)=><details className="quest-stage" key={stage.id} open={index===0}><summary><span>{stage.name}</span><span className="quest-hint">{stage.steps.flatMap(s=>s.tasks).filter(t=>progress[taskProgressKey(quest,t)]).length}/{stage.steps.flatMap(s=>s.tasks).length} done</span></summary><div className="quest-stage-body">{stage.steps.map((step,i)=><section className="quest-step" key={step.id}><h3><span className="quest-step-number">{i+1}</span>{step.title}</h3><div className="quest-objectives">{step.tasks.map(task=><div className="quest-objective" key={task.id}><label className="quest-check"><input type="checkbox" checked={Boolean(progress[taskProgressKey(quest,task)])} onChange={()=>toggle(task)}/><span>{task.text}</span></label>{(task.fish.length>0||task.rods.length>0||task.mutations.length>0||Boolean(task.solutions?.length))&&<details className="quest-objective-help"><summary>Fish, rods & catch guidance</summary><CatchHelp task={task} data={data}/></details>}</div>)}</div></section>)}</div></details>):<p>No numbered walkthrough is published for this NPC yet. Use the source link and your Quest Book; the available notes are below.</p>}<Blocks data={data} blocks={quest.notes}/>{archived.length>0&&<details className="quest-archived"><summary>{archived.length} archived quest{archived.length===1?'':'s'} on this NPC’s page</summary><ul>{archived.map(s=><li key={s.id}>{s.name} — unavailable / historical source section</li>)}</ul></details>}</>}
  {view==='checklist'&&<><h2>Fish & rod checklist</h2><p className="quest-info">Objectives are kept intact so “or” alternatives, quantities, and combinations stay clear. Mark them complete in the step-by-step guide.</p>{checklist.length?checklist.map(task=><section className="quest-checklist-entry" key={task.id}><h3>{task.text}</h3><CatchHelp task={task} data={data}/></section>):<p>No specific fish, mutation, or rod is named in the structured objectives. Check the numbered guide and solution notes for generic targets or riddles.</p>}<Blocks data={data} blocks={quest.notes.filter(b=>b.tables.length>0)}/></>}
  {view==='rewards'&&<><h2>Rewards & completion</h2>{quest.rewards.length?<ul className="quest-rewards">{quest.rewards.map((text,i)=><li key={i}>{text}</li>)}</ul>:<p>The source does not list a structured reward for this guide. Check the quest giver or source page.</p>}<p className="quest-info">Rewards can depend on the stage, choices, and event. Return to the NPC or destination named in each objective and confirm completion in the Quest Book. Checking a box here does not claim rewards in the game.</p></>}
 </div></div></>;
}
export default function QuestHelper({initialData}:{initialData:QuestDataset}) {
 const [data,setData]=useState(initialData),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [query,setQuery]=useState(''),[filters,setFilters]=useState<QuestFilters>({...questFilterDefaults}),[sort,setSort]=useState('name-asc'),[page,setPage]=useState(1),[selectedPage,setSelectedPage]=useState(''),[urlReady,setUrlReady]=useState(false);
 const [progress,setProgress]=useState<Record<string,true>>({}),[progressReady,setProgressReady]=useState(false),[storageAvailable,setStorageAvailable]=useState(true),[shareStatus,setShareStatus]=useState(''),[shareLink,setShareLink]=useState(''),[resetRequested,setResetRequested]=useState(false);
 const [mobile,setMobile]=useState(false),[filtersOpen,setFiltersOpen]=useState(false);
 const dialogRef=useRef<HTMLDialogElement>(null),triggerRef=useRef<HTMLElement|null>(null),refreshController=useRef<AbortController|null>(null);
 const results=useMemo(()=>findQuests(data.quests,query,filters,sort),[data.quests,query,filters,sort]),options=useMemo(()=>questOptions(data.quests),[data.quests]);
 const selected=data.quests.find(q=>q.page===selectedPage),pageCount=Math.max(1,Math.ceil(results.length/pageSize)),currentPage=Math.min(page,pageCount),visible=results.slice((currentPage-1)*pageSize,currentPage*pageSize);
 async function refresh(force=false){refreshController.current?.abort();const controller=new AbortController();refreshController.current=controller;const timeout=window.setTimeout(()=>controller.abort(),60000);setLoading(true);setError('');try{const response=await fetch('/api/quests.json?schema=4',{method:force?'POST':'GET',cache:'no-store',signal:controller.signal});if(!response.ok)throw new Error('Refresh failed');const next=await response.json() as QuestDataset;if(!Array.isArray(next.quests)||!next.quests.length||!Array.isArray(next.fish)||!Array.isArray(next.rods)||!Array.isArray(next.mutations)||!Number.isFinite(Date.parse(next.fetchedAt))||next.quests.some(q=>!q||typeof q.page!=='string'||!Array.isArray(q.stages)||!Array.isArray(q.notes)))throw new Error('Invalid quest data');setData(current=>Date.parse(next.fetchedAt)<Date.parse(current.fetchedAt)?{...current,mode:next.mode,notice:next.notice}:next);}catch{if(refreshController.current===controller)setError('Refresh unavailable. Saved guides and your checklist remain available.');}finally{window.clearTimeout(timeout);if(refreshController.current===controller)setLoading(false);}}
 useEffect(()=>{const media=window.matchMedia('(max-width:767px)'),sync=()=>setMobile(media.matches);sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync);},[]);
 useEffect(()=>{try{visitProgress=readQuestProgress(localStorage.getItem(STORAGE));setProgress(visitProgress);}catch{setProgress(visitProgress);setStorageAvailable(false);}setProgressReady(true);const sync=(event:StorageEvent)=>{if(event.key===STORAGE){visitProgress=readQuestProgress(event.newValue);setProgress(visitProgress);}};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);},[]);
 useEffect(()=>{if(!progressReady)return;visitProgress=progress;try{localStorage.setItem(STORAGE,JSON.stringify(progress));}catch{setStorageAvailable(false);}},[progress,progressReady]);
 useEffect(()=>{const readUrl=()=>{const p=new URLSearchParams(window.location.search);setQuery(p.get('q')||'');setSelectedPage(p.get('quest')||'');setFilters({location:p.get('location')||'',type:p.get('type')||'',status:p.has('status')?['available','unavailable','unknown'].includes(p.get('status')||'')?p.get('status')!:'':questFilterDefaults.status});setSort(['name-asc','name-desc','location-asc'].includes(p.get('sort')||'')?p.get('sort')!:'name-asc');const requested=Number(p.get('page'));setPage(Number.isFinite(requested)?Math.max(1,Math.floor(requested)):1);setUrlReady(true);};readUrl();void refresh();const interval=window.setInterval(()=>void refresh(),30*60*1000);window.addEventListener('popstate',readUrl);return()=>{window.removeEventListener('popstate',readUrl);window.clearInterval(interval);refreshController.current?.abort();};},[]);
 useEffect(()=>{if(!urlReady)return;const p=new URLSearchParams();if(query)p.set('q',query);if(selectedPage)p.set('quest',selectedPage);if(filters.location)p.set('location',filters.location);if(filters.type)p.set('type',filters.type);if(filters.status!==questFilterDefaults.status)p.set('status',filters.status);if(sort!=='name-asc')p.set('sort',sort);if(page>1)p.set('page',String(page));window.history.replaceState(null,'',`${window.location.pathname}${p.size?'?'+p.toString():''}`);},[urlReady,query,selectedPage,filters,sort,page]);
 useEffect(()=>{const dialog=dialogRef.current;if(!selected||!dialog)return;const y=window.scrollY,body=document.body,saved={position:body.style.position,top:body.style.top,width:body.style.width,overflow:body.style.overflow};dialog.showModal();Object.assign(body.style,{position:'fixed',top:`-${y}px`,width:'100%',overflow:'hidden'});return()=>{dialog.close();Object.assign(body.style,saved);window.scrollTo(0,y);triggerRef.current?.focus({preventScroll:true});};},[selected?.page]);
 function close(){setSelectedPage('');setShareStatus('');setShareLink('');setResetRequested(false);}
 function choose(q:Quest,trigger:HTMLElement){triggerRef.current=trigger;setSelectedPage(q.page);setShareStatus('');setShareLink('');setResetRequested(false);}
 function toggle(task:QuestTask){if(!selected)return;const key=taskProgressKey(selected,task);setProgress(current=>{const next={...current};if(next[key])delete next[key];else next[key]=true;return next;});}
 function reset(){if(!selected)return;setProgress(current=>Object.fromEntries(Object.entries(current).filter(([key])=>!key.startsWith(`${selected.id}:`))) as Record<string,true>);setResetRequested(false);}
 async function share(){if(!selected)return;const url=new URL(window.location.pathname,window.location.origin);url.searchParams.set('quest',selected.page);try{await navigator.clipboard.writeText(url.href);setShareStatus('Guide link copied.');}catch{setShareLink(url.href);setShareStatus('Copy the guide link below.');}}
 function filter(key:keyof QuestFilters,value:string){setFilters(current=>({...current,[key]:value}));setPage(1);}
 const stageCount=(q:Quest)=>q.stages.filter(s=>!s.archived).length;
 return <section className="fish-database quest-helper" aria-label="Searchable quest helper"><header className="fish-page-heading flex flex-wrap items-start justify-between gap-lg mb-lg"><div><p className="text-accent text-xs font-semibold uppercase tracking-wide mb-xs">Fischipedia data, easier to follow</p><h1 className="text-3xl font-semibold tracking-tight">Quest Helper</h1><p className="text-mute mt-xs">Find a quest. Plan your catches. Follow the steps.</p></div><div className="fish-source-summary"><span className={`fish-data-badge ${data.mode==='snapshot'||error?'fish-data-badge-snapshot':''}`}>{loading?'Checking wiki data…':error||data.mode==='snapshot'?'Saved wiki snapshot':'Wiki API data'}</span><p>Source checked: {timestamp(data.fetchedAt)}</p><button className="fish-refresh" disabled={loading} onClick={()=>void refresh(true)}>{loading?'Refreshing…':'Refresh data'} ↻</button></div></header>{(error||!loading&&data.notice)&&<p className="fish-data-notice" role="status">{error||data.notice}</p>}
 <div className="fish-controls"><div className="fish-search-bar"><label className="fish-search"><span aria-hidden="true">⌕</span><span className="sr-only">Search quests, NPCs, fish, or rewards</span><input type="search" value={query} placeholder="Search quests, NPCs, fish, or rewards" onChange={e=>{setQuery(e.target.value);setPage(1);}}/>{query&&<button aria-label="Clear search" onClick={()=>{setQuery('');setPage(1);}}>×</button>}</label><button className="fish-filter-toggle" aria-expanded={filtersOpen} aria-controls="quest-filters" onClick={()=>setFiltersOpen(open=>!open)}>Filters</button></div><div id="quest-filters" className="fish-filter-panel" hidden={mobile&&!filtersOpen}><div className="quest-filter-heading"><h2>Filter quests</h2><button className="fish-clear" onClick={()=>{setQuery('');setFilters({...questFilterDefaults});setPage(1);}}>Reset filters</button></div><div className="fish-filters quest-filters">{(['location','type'] as const).map(key=><label className="fish-filter" key={key}><span>{key==='location'?'Location':'Quest type'}</span><select value={filters[key]} onChange={e=>filter(key,e.target.value)}><option value="">{key==='location'?'All locations':'All quest types'}</option>{options[key].map(value=><option value={value} key={value}>{value}</option>)}</select></label>)}<label className="fish-filter"><span>Availability</span><select value={filters.status} onChange={e=>filter('status',e.target.value)}><option value="available">Available</option><option value="">All</option><option value="unavailable">Unavailable / archived</option><option value="unknown">Needs checking</option></select></label></div><details className="fish-data-legend"><summary>How to read these guides</summary><p>Quests are grouped by NPC, including multiple quests and long questlines. Available is the wiki’s NPC removal flag; event access, prerequisites, and per-player progress can still apply. The wiki may omit quests or steps. Variable targets must be checked in your Quest Book.</p><p>Guides and catch data are checked when opened and every 30 minutes, with a server cache of up to 30 minutes. Manual refresh is limited to once a minute per server instance. Changed wiki pages update automatically; failed checks retain saved data. Checklist progress stays on your device and does not sync with the game.</p></details><button className="fish-filter-done" onClick={()=>setFiltersOpen(false)}>Show {results.length.toLocaleString('en-US')} guides</button></div></div>
 <div className="quest-results"><div className="fish-results-heading"><p role="status" aria-live="polite"><strong>{results.length.toLocaleString('en-US')}</strong> quest guides<span> of {data.quests.length.toLocaleString('en-US')} wiki NPC entries</span></p><label className="fish-sort"><span>Sort</span><select value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="name-asc">Name A–Z</option><option value="name-desc">Name Z–A</option><option value="location-asc">Location A–Z</option></select></label></div>
 {results.length?<><div className="fish-table-scroll" tabIndex={0} role="region" aria-label="Quest results table"><table className="fish-table quest-table"><caption className="sr-only">Click anywhere in a row to open its full quest guide.</caption><thead><tr>{['Quest / questline','Location','Quest giver','Rewards / unlocks','Guide'].map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(q=><tr key={q.id} onClick={e=>choose(q,e.currentTarget.querySelector<HTMLElement>('button')??e.currentTarget)}><td><button className="fish-name" aria-haspopup="dialog" aria-controls="quest-guide-dialog" onClick={e=>{e.stopPropagation();choose(q,e.currentTarget);}}>{q.name}</button><span className="fish-row-note">{q.type} · {statusLabel(q.status)}</span></td><td>{q.locations.join(' · ')||'Not listed'}</td><td>{q.npc}</td><td>{q.rewards[0]?.slice(0,110)||'See guide / source'}{(q.rewards[0]?.length??0)>110?'…':''}</td><td><span>{stageCount(q)} quest{stageCount(q)===1?'':'s'}</span>{q.incomplete&&<span className="fish-row-note">Source incomplete</span>}<span className="fish-row-note">{questTasks(q).filter(t=>progress[taskProgressKey(q,t)]).length}/{questTasks(q).length} done</span></td></tr>)}</tbody></table></div><ul className="fish-mobile-cards" aria-label="Quest results">{visible.map(q=><li key={q.id}><button className="fish-mobile-card" onClick={e=>choose(q,e.currentTarget)} aria-haspopup="dialog" aria-controls="quest-guide-dialog"><span className="fish-card-heading"><span className="fish-card-name">{q.name}</span><span aria-hidden="true">↗</span></span><span className="fish-card-region">{q.npc} · {q.locations.join(' · ')||'Location not listed'}</span><span className="fish-card-tags"><span className="fish-tag">{statusLabel(q.status)}</span><span className="fish-tag">{q.type}</span><span className="fish-tag">{stageCount(q)} quests</span></span><span className="quest-hint">{q.rewards[0]?.slice(0,130)||'Open the guide for objectives and requirements.'}</span></button></li>)}</ul><div className="fish-pagination"><span>{(currentPage-1)*pageSize+1}–{Math.min(currentPage*pageSize,results.length)} of {results.length}</span><div className="fish-page-buttons"><button aria-label="Previous page" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>‹</button><span>Page {currentPage} of {pageCount}</span><button aria-label="Next page" disabled={currentPage===pageCount} onClick={()=>setPage(currentPage+1)}>›</button></div></div></>:<div className="fish-results-empty"><h2>No quests found</h2><p>Try a different search or change the availability filter.</p><button className="fish-clear" onClick={()=>{setQuery('');setFilters({...questFilterDefaults});setPage(1);}}>Reset search & filters</button></div>}<p className="fish-results-note">Click a quest row or tap a card for the expanded guide. Requirements reflect wiki documentation, not live game state.</p></div>
 {selectedPage&&!selected&&<p className="fish-data-notice">The linked quest guide was not found in this dataset.</p>}
 <dialog className="quest-guide-dialog" id="quest-guide-dialog" ref={dialogRef} aria-labelledby="quest-guide-title" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close();}}>{selected&&<><header className="quest-guide-header"><div><p className="quest-eyebrow">Quest Helper</p><h2 id="quest-guide-title">{selected.name}</h2><p>{selected.npc} · {selected.locations.join(' · ')||'Location not listed'}</p><span className={`fish-tag ${selected.status!=='available'?'fish-tag-warning':''}`}>{statusLabel(selected.status)}</span></div><button className="quest-modal-close" aria-label="Close quest guide" autoFocus onClick={close}>×</button></header><Guide key={selected.page} quest={selected} data={data} progress={progress} toggle={toggle} storageAvailable={storageAvailable} share={()=>void share()} shareStatus={shareStatus}/>{shareLink&&<label className="quest-share-field">Guide link<input readOnly value={shareLink} onFocus={e=>e.target.select()}/></label>}<footer className="quest-guide-footer"><div><span>Source checked: {timestamp(data.fetchedAt)}</span>{resetRequested?<span className="quest-reset-confirm">Reset this guide’s saved progress? <button onClick={reset}>Reset</button><button onClick={()=>setResetRequested(false)}>Cancel</button></span>:<button className="fish-clear" onClick={()=>setResetRequested(true)}>Reset this guide’s progress</button>}</div><a href={selected.url} target="_blank" rel="noopener noreferrer">View wiki source ↗</a></footer></>}</dialog>
 </section>;
}
